name: Call Remote E2E

on:
  pull_request:
    branches: [stage]

jobs:
  call-e2e:
    uses: microservices-final-project/ci-templates/.github/workflows/call-remote-e2e.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
